# This is a basic workflow to help you get started with Actions

name : react_deploy_surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
 
    - name: Install MATERIAL UI CORE
      run: npm install @material-ui/core
      
    - name: Install MATERIAL UI Icon
      run: npm install @material-ui/icons
      
    - name: Install react chart and chart js
      run: npm install --save react-chartjs-2 chart.js
      
    
 
    - name: Build React App
      run: yarn build
      
    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./build faisalrahman36_covid19_tracker.surge.sh --token ${{ secrets.SURGE_TOKEN}} 
